import { useState, useEffect, type FC } from 'react';
import {
  PageHeader,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Badge,
  Button,
  Breadcrumb,
  EmptyState,
  LoadingSpinner,
} from '../../components/ui';
import { getHealth } from '../../services';

export const AssignmentsManager: FC = () => {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    getHealth().finally(() => {
      if (mounted) setIsLoading(false);
    });
    return () => {
      mounted = false;
    };
  }, []);

  return (
    <div>
      <PageHeader
        title="Assignment Matrix"
        description="Allocate projects to judges with automated conflict-of-interest avoidance and balanced review distribution."
        badge={<Badge variant="neutral" size="sm">Distribution Desk</Badge>}
        breadcrumbs={
          <Breadcrumb
            items={[
              { label: 'Dogfood 2026', href: '/' },
              { label: 'Organizer', href: '/organizer' },
              { label: 'Assignments' },
            ]}
          />
        }
        actions={
          <Button
            variant="outline"
            size="sm"
            leftIcon="refresh"
            isLoading={isLoading}
            onClick={() => {
              setIsLoading(true);
              getHealth().finally(() => setIsLoading(false));
            }}
          >
            Check Matrix
          </Button>
        }
      />

      {isLoading ? (
        <Card>
          <CardContent style={{ padding: 'var(--space-8)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 'var(--space-3)' }}>
            <LoadingSpinner size="md" />
            <span style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)' }}>
              Checking assignment distribution from local backend...
            </span>
          </CardContent>
        </Card>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
          <Card>
            <CardHeader
              actions={<Badge variant="neutral">Service: /api/v1/events/:id/judges/assign (Pending)</Badge>}
            >
              <CardTitle>Judge-Project Assignment Matrix</CardTitle>
              <CardDescription>
                Pairings between submissions and evaluating judges for blind scoring rounds.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <EmptyState
                icon="file-text"
                title="Organizer data is not available yet"
                description="No assignment matrices have been generated by the backend (/api/v1/events/:id/judges/assign). Once project submissions close and organizers trigger the distribution algorithm, the assignment table will populate here."
              />
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
};
