import { useState, useEffect, type FC } from 'react';
import {
  PageHeader,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  StatusBadge,
  Badge,
  Button,
  Breadcrumb,
  EmptyState,
  LoadingSpinner,
  Icon,
} from '../../components/ui';
import { getHealth } from '../../services';

export const Certificate: FC = () => {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    getHealth().finally(() => {
      if (mounted) setIsLoading(false);
    });
    return () => {
      mounted = false;
    };
  }, []);

  return (
    <div>
      <PageHeader
        title="Participation Certificate"
        description="Official cryptographically verifiable certificate issued upon completion of all hackathon requirements."
        badge={<StatusBadge status="Pending" />}
        breadcrumbs={
          <Breadcrumb
            items={[
              { label: 'Dogfood 2026', href: '/' },
              { label: 'Participant', href: '/participant' },
              { label: 'Certificate' },
            ]}
          />
        }
        actions={
          <Button
            variant="outline"
            size="sm"
            leftIcon="refresh"
            isLoading={isLoading}
            onClick={() => {
              setIsLoading(true);
              getHealth().finally(() => setIsLoading(false));
            }}
          >
            Check Availability
          </Button>
        }
      />

      {isLoading ? (
        <Card>
          <CardContent style={{ padding: 'var(--space-8)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 'var(--space-3)' }}>
            <LoadingSpinner size="md" />
            <span style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)' }}>
              Checking certificate availability from local backend...
            </span>
          </CardContent>
        </Card>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
          {/* Main Certificate State Card */}
          <Card>
            <CardHeader
              actions={<Badge variant="neutral">Status: Unavailable</Badge>}
            >
              <CardTitle>Verified Credential</CardTitle>
              <CardDescription>
                Self-contained, offline-printable PDF certificate with participant and project details.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <EmptyState
                icon="award"
                title="Certificate is not available yet"
                description="Official certificates are issued by the platform following event conclusion, submission verification, and results finalization. Once generated by organizers, you will be able to view and print your verified certificate directly."
              />
            </CardContent>
          </Card>

          {/* Certificate Generation Spec */}
          <div
            style={{
              padding: '16px 20px',
              backgroundColor: 'var(--bg-surface)',
              border: '1px solid var(--border-default)',
              borderRadius: 'var(--radius-lg)',
              display: 'flex',
              alignItems: 'center',
              gap: 'var(--space-3)',
            }}
          >
            <Icon name="file" size={18} style={{ color: 'var(--color-primary-600)' }} />
            <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)' }}>
              All certificates generated by Dogfood 2026 Hackathon OS are created offline using native vector rendering and do not depend on external cloud PDF rendering services.
            </span>
          </div>
        </div>
      )}
    </div>
  );
};
